### ISSUE TITLE
Dropdownliste til valg af skole 

### ISSUE THREAD

**Issue by Nyborg1** [mapcentia/skolevej#1]
Efter angivelse af udgangsadresse skal man i brugerfladen blot kunne vælge én skole i en drop downliste

**Comment by mapcentia** [comment]
Det kan laves relativt nemt, ved at trække en listen med skoler ud i opstarten

**Comment by mapcentia** [comment]
@Nyborg1 Dette er nu lavet

**Comment by Nyborg1** [comment]
Det virker fint
