### ISSUE TITLE
Print af kort med ruter fejler 

### ISSUE THREAD

**Issue by Nyborg1** [mapcentia/skolevej#4]

**Comment by mapcentia** [comment]
Skolevej modulets tegninger kommer nu med på print.

**Comment by Nyborg1** [comment]
Har du opdateret det på geofyn?
Jeg synes ikke at ruterne vises på print
![skolegis_print_fejl](https://github.com/mapcentia/skolevej/assets/95336810/e4444e09-c990-4e98-8ef1-4158b60b1de1)
